/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author edu-1
 */
public class ViewMenu extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenu
     */
    public ViewMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        mAlum = new javax.swing.JMenu();
        miCargarAlum = new javax.swing.JMenuItem();
        miBuscarAlumXID = new javax.swing.JMenuItem();
        miBuscarAlumXDNI = new javax.swing.JMenuItem();
        miAlumActivos = new javax.swing.JMenuItem();
        miModAlum = new javax.swing.JMenuItem();
        miBajaAlum = new javax.swing.JMenuItem();
        miAltaAlum = new javax.swing.JMenuItem();
        mMat = new javax.swing.JMenu();
        miCargarMat = new javax.swing.JMenuItem();
        miBuscarMat = new javax.swing.JMenuItem();
        miModMat = new javax.swing.JMenuItem();
        miMatActivas = new javax.swing.JMenuItem();
        miBajaMat = new javax.swing.JMenuItem();
        miAltaMat = new javax.swing.JMenuItem();
        mIns = new javax.swing.JMenu();
        miCargarIns = new javax.swing.JMenuItem();
        miVerIns = new javax.swing.JMenuItem();
        miInsXAlum = new javax.swing.JMenuItem();
        miMatCursadasXAlum = new javax.swing.JMenuItem();
        miMatNoCursadasXAlum = new javax.swing.JMenuItem();
        miModNota = new javax.swing.JMenuItem();
        miBorrarIns = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setName("Universidad ULP"); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        mAlum.setText("Alumnos");

        miCargarAlum.setText("Cargar alumno");
        miCargarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCargarAlumActionPerformed(evt);
            }
        });
        mAlum.add(miCargarAlum);

        miBuscarAlumXID.setText("Buscar alumno por ID");
        mAlum.add(miBuscarAlumXID);

        miBuscarAlumXDNI.setText("Buscar alumno por DNI");
        mAlum.add(miBuscarAlumXDNI);

        miAlumActivos.setText("Ver alumnos activos");
        mAlum.add(miAlumActivos);

        miModAlum.setText("Modificar alumno");
        mAlum.add(miModAlum);

        miBajaAlum.setText("Dar de baja un alumno");
        mAlum.add(miBajaAlum);

        miAltaAlum.setText("Dar de alta un alumno");
        mAlum.add(miAltaAlum);

        jMenuBar2.add(mAlum);

        mMat.setText("Materias");

        miCargarMat.setText("Cargar materia");
        mMat.add(miCargarMat);

        miBuscarMat.setText("Buscar materia");
        mMat.add(miBuscarMat);

        miModMat.setText("Modificar materia");
        mMat.add(miModMat);

        miMatActivas.setText("Ver materias activas");
        mMat.add(miMatActivas);

        miBajaMat.setText("Dar de baja una materia");
        mMat.add(miBajaMat);

        miAltaMat.setText("Dar de alta una materia");
        mMat.add(miAltaMat);

        jMenuBar2.add(mMat);

        mIns.setText("Inscripciones");

        miCargarIns.setText("Cargar inscripcion");
        mIns.add(miCargarIns);

        miVerIns.setText("Ver inscripciones");
        mIns.add(miVerIns);

        miInsXAlum.setText("Inscripciones de un alumno");
        mIns.add(miInsXAlum);

        miMatCursadasXAlum.setText("Materias cursadas de un alumno");
        mIns.add(miMatCursadasXAlum);

        miMatNoCursadasXAlum.setText("Materias no cursadas de un alumno");
        mIns.add(miMatNoCursadasXAlum);

        miModNota.setText("Modificar una nota");
        mIns.add(miModNota);

        miBorrarIns.setText("Borrar una inscripcion");
        mIns.add(miBorrarIns);

        jMenuBar2.add(mIns);

        mSalir.setText("Salir");

        miSalir.setText("Salir del sistema");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mSalir.add(miSalir);

        jMenuBar2.add(mSalir);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jDesktopPane1.getAccessibleContext().setAccessibleName("Universidad ULP");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    private void miCargarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCargarAlumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miCargarAlumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu mAlum;
    private javax.swing.JMenu mIns;
    private javax.swing.JMenu mMat;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuItem miAltaAlum;
    private javax.swing.JMenuItem miAltaMat;
    private javax.swing.JMenuItem miAlumActivos;
    private javax.swing.JMenuItem miBajaAlum;
    private javax.swing.JMenuItem miBajaMat;
    private javax.swing.JMenuItem miBorrarIns;
    private javax.swing.JMenuItem miBuscarAlumXDNI;
    private javax.swing.JMenuItem miBuscarAlumXID;
    private javax.swing.JMenuItem miBuscarMat;
    private javax.swing.JMenuItem miCargarAlum;
    private javax.swing.JMenuItem miCargarIns;
    private javax.swing.JMenuItem miCargarMat;
    private javax.swing.JMenuItem miInsXAlum;
    private javax.swing.JMenuItem miMatActivas;
    private javax.swing.JMenuItem miMatCursadasXAlum;
    private javax.swing.JMenuItem miMatNoCursadasXAlum;
    private javax.swing.JMenuItem miModAlum;
    private javax.swing.JMenuItem miModMat;
    private javax.swing.JMenuItem miModNota;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JMenuItem miVerIns;
    // End of variables declaration//GEN-END:variables
}
