/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.AlumnoData;
import persistencia.Conexion;
import persistencia.InscripcionData;
import persistencia.MateriaData;

/**
 *
 * @author edu-1
 */
public class ViewInscripcion extends javax.swing.JInternalFrame {
    DefaultTableModel tabla;
    private static InscripcionData inscripData;
    private static AlumnoData alumnoData;
    private static MateriaData materiaData;
    private List<Alumno> listaA;
    private Inscripcion inscripcion;
    private Materia materia;
    private List<Materia> matTotal;
    private Alumno alumno;
    private Conexion con;

    /**
     * Creates new form ViewInscripcion
     */
    public ViewInscripcion() {
        initComponents();
        tabla = new DefaultTableModel();
        inscripData = new InscripcionData();
        materiaData = new MateriaData();
        alumnoData = new AlumnoData();
        listaA = (ArrayList<Alumno>) alumnoData.listarAlumnos();
        agregarAlumno();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboAlumno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JTable();
        btnMostrarInscripta = new javax.swing.JRadioButton();
        btnNoInscripta = new javax.swing.JRadioButton();
        btnInscribir = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Alumno: ");

        jComboAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAlumnoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Listado de Materias");

        jLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "nombre", "año"
            }
        ));
        jScrollPane1.setViewportView(jLista);

        btnMostrarInscripta.setText("Inscriptas");
        btnMostrarInscripta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInscriptaActionPerformed(evt);
            }
        });

        btnNoInscripta.setText("No Inscriptas");
        btnNoInscripta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoInscriptaActionPerformed(evt);
            }
        });

        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        btnAnular.setText("Anular Inscripcion");

        btnSalir.setText("   Salir   ");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInscribir)
                        .addGap(38, 38, 38)
                        .addComponent(btnAnular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnMostrarInscripta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNoInscripta)
                                .addGap(10, 10, 10)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarInscripta)
                    .addComponent(btnNoInscripta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir)
                    .addComponent(btnAnular)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAlumnoActionPerformed


    }//GEN-LAST:event_jComboAlumnoActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        String selectedItem = jComboAlumno.getSelectedItem().toString();
        String[] parts = selectedItem.split(" ");
        int id = Integer.parseInt(parts[0]);
        
        int filaSelec = jLista.getSelectedRow();
        
        if (filaSelec!=-1) {
            int idMat = (Integer)jLista.getValueAt(filaSelec, 0);
            inscripData.guardarIncripcion(new Inscripcion(0, id, idMat));
        }
        inscripData.guardarIncripcion(inscripcion);

    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnNoInscriptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoInscriptaActionPerformed
        btnMostrarInscripta.setSelected(false);
        btnInscribir.setEnabled(true);
        btnAnular.setEnabled(false);
        String selectedItem = jComboAlumno.getSelectedItem().toString();
        String[] parts = selectedItem.split(" ");
        int id = Integer.parseInt(parts[0]);
        List<Materia> lisa = new ArrayList<>();
        String fila[] = new String[3];
        tabla.addColumn("id");
        tabla.addColumn("nombre");
        tabla.addColumn("año");
        lisa = inscripData.obtenerMateriasNOCursadas(id);
        for (int i = 0; i < lisa.size(); i++) {
            fila[0] = lisa.get(i).getIdMateria() + "";
            fila[1] = lisa.get(i).getNombre();
            fila[2] = lisa.get(i).getAnio() + "";
            tabla.addRow(fila);
        }
        jLista.setModel(tabla);
    }//GEN-LAST:event_btnNoInscriptaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMostrarInscriptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInscriptaActionPerformed
        btnNoInscripta.setSelected(false);
        btnInscribir.setEnabled(false);
        btnAnular.setEnabled(true);
        String selectedItem = jComboAlumno.getSelectedItem().toString();
        String[] parts = selectedItem.split(" ");
        int id = Integer.parseInt(parts[0]);
        List<Materia> lisa = new ArrayList<>();
        String fila[] = new String[3];
        tabla.addColumn("id");
        tabla.addColumn("nombre");
        tabla.addColumn("año");
        lisa = inscripData.obtenerMateriasCursadas(id);
        for (int i = 0; i < lisa.size(); i++) {
            fila[0] = lisa.get(i).getIdMateria() + "";
            fila[1] = lisa.get(i).getNombre();
            fila[2] = lisa.get(i).getAnio() + "";
            tabla.addRow(fila);
        }
        jLista.setModel(tabla);
    }//GEN-LAST:event_btnMostrarInscriptaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JRadioButton btnMostrarInscripta;
    private javax.swing.JRadioButton btnNoInscripta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> jComboAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTable jLista;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void agregarAlumno() {
        Alumno lista = new Alumno();
        for (Iterator<Alumno> it = listaA.iterator(); it.hasNext();) {
            lista = it.next();
            jComboAlumno.addItem(lista.getIdAlumno() + " " + lista.getApellido() + " " + lista.getNombre() + " " + lista.getDni());
        }
    }

    public void borrarTabla() {
        if (tabla != null) {
            int a = tabla.getRowCount() - 1;
            for (int i = a; i > 0; i--) {
                tabla.removeRow(i);
            }
        }
    }

}
