/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import entidades.Alumno;

/**
 *
 * @author edu-1
 */
public class ViewMenu extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenu
     */
    public ViewMenu() {
        initComponents();
        this.setTitle("Universidad ULP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEscritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuAlumno = new javax.swing.JMenu();
        jAlumno = new javax.swing.JMenuItem();
        jMenuMateria = new javax.swing.JMenu();
        jMateria = new javax.swing.JMenuItem();
        jMenuInscripcion = new javax.swing.JMenu();
        jInscripcion = new javax.swing.JMenuItem();
        jMenuNota = new javax.swing.JMenu();
        jNotasEditar = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jListAlumnxMateria = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEscritorio.setName("Universidad ULP"); // NOI18N

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenuAlumno.setText("Alumnos");

        jAlumno.setText("Formulario de Alumnos");
        jAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumno.add(jAlumno);

        jMenuBar2.add(jMenuAlumno);

        jMenuMateria.setText("Materias");

        jMateria.setText("Formulario de Materias");
        jMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMateriaActionPerformed(evt);
            }
        });
        jMenuMateria.add(jMateria);

        jMenuBar2.add(jMenuMateria);

        jMenuInscripcion.setText("Inscripciones");

        jInscripcion.setText("Manejo de Inscripciones");
        jInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInscripcionActionPerformed(evt);
            }
        });
        jMenuInscripcion.add(jInscripcion);

        jMenuBar2.add(jMenuInscripcion);

        jMenuNota.setText("Carga de Notas");

        jNotasEditar.setText("Manipulacion de Notas");
        jMenuNota.add(jNotasEditar);

        jMenuBar2.add(jMenuNota);

        jMenuConsulta.setText("Consultas");

        jListAlumnxMateria.setText("Listado de Alumnos por Materias");
        jMenuConsulta.add(jListAlumnxMateria);

        jMenuBar2.add(jMenuConsulta);

        jMenuSalir.setText("Salir");

        jSalir.setText("Salir del sistema");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jSalir);

        jMenuBar2.add(jMenuSalir);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );

        jEscritorio.getAccessibleContext().setAccessibleName("Universidad ULP");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    private void jMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMateriaActionPerformed
    
        jEscritorio.removeAll();
        jEscritorio.repaint();
        ViewMateria materia = new ViewMateria();
        materia.setVisible(true);
        jEscritorio.add(materia);
                                      
        
    }//GEN-LAST:event_jMateriaActionPerformed

    private void jAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlumnoActionPerformed
        ViewAlumno va = new ViewAlumno();
        jEscritorio.removeAll();
        jEscritorio.repaint();
        va.setVisible(true);
        jEscritorio.add(va);
    }//GEN-LAST:event_jAlumnoActionPerformed

    private void jInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInscripcionActionPerformed
        // TODO add your handling code here:
         jEscritorio.removeAll();
        jEscritorio.repaint();
        ViewInscripcion inscrip = new ViewInscripcion();
        inscrip.setVisible(true);
        jEscritorio.add(inscrip);
                                      
    }//GEN-LAST:event_jInscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAlumno;
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenuItem jInscripcion;
    private javax.swing.JMenuItem jListAlumnxMateria;
    private javax.swing.JMenuItem jMateria;
    private javax.swing.JMenu jMenuAlumno;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenu jMenuInscripcion;
    private javax.swing.JMenu jMenuMateria;
    private javax.swing.JMenu jMenuNota;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenuItem jNotasEditar;
    private javax.swing.JMenuItem jSalir;
    // End of variables declaration//GEN-END:variables
}
