/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import persistencia.AlumnoData;
import persistencia.InscripcionData;
import persistencia.MateriaData;

/**
 *
 * @author thefl
 */
public class ViewAlumXMat extends javax.swing.JInternalFrame {
    private List<Materia> listaM;
    private DefaultTableModel tabla;
    private static AlumnoData alumnoData;
    private static MateriaData materiaData;
    private static InscripcionData inscripData;
    /**
     * Creates new form ViewMatXAlum
     */
    public ViewAlumXMat() {
        initComponents();
        tabla = new DefaultTableModel();
        alumnoData = new AlumnoData();
        inscripData = new InscripcionData();
        materiaData = new MateriaData();
        crearTabla();
        listaM = (ArrayList<Materia>) materiaData.listarMaterias();
        agregarMateria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbListadoAXM = new javax.swing.JLabel();
        lbMat = new javax.swing.JLabel();
        jComboMateria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JTable();
        bSalir = new javax.swing.JButton();

        lbListadoAXM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbListadoAXM.setText("Listado de Alumnos por Materia");

        lbMat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbMat.setText("Materia");

        jComboMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMateriaActionPerformed(evt);
            }
        });

        jLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Nota"
            }
        ));
        jScrollPane1.setViewportView(jLista);

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bSalir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(lbMat)
                            .addGap(18, 18, 18)
                            .addComponent(jComboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbListadoAXM)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbListadoAXM)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMat)
                    .addComponent(jComboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void jComboMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMateriaActionPerformed
        borrarTabla();
        String selectedItem = jComboMateria.getSelectedItem().toString();
        String[] parts = selectedItem.split(" ");
        int idM = Integer.parseInt(parts[0]);
        List<Alumno> lisa = inscripData.obtenerAlumnosXMateria(idM);
        String fila[] = new String[3];
        Double nota=0.0;
        List<Inscripcion> lis;
        for (int i = 0; i < lisa.size(); i++) {
            fila[0] = lisa.get(i).getIdAlumno() + "";
            fila[1] = lisa.get(i).getNombre();
            lis = inscripData.obtenerInscripcionesPorAlumno(lisa.get(i).getIdAlumno());
            for (Inscripcion li : lis) {
                if (li.getMateriaId().getIdMateria()==idM && li.getAlumnoId().getIdAlumno()==lisa.get(i).getIdAlumno()) {
                    nota = li.getNota();
                }
            }
            fila[2] = nota+"";
            tabla.addRow(fila);
        }
        jLista.setModel(tabla);
    }//GEN-LAST:event_jComboMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> jComboMateria;
    private javax.swing.JTable jLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbListadoAXM;
    private javax.swing.JLabel lbMat;
    // End of variables declaration//GEN-END:variables

    public void crearTabla() {
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("nombre");
        columnas.add("nota");
        for (Object iter : columnas) {
            tabla.addColumn(iter);
        }
        jLista.setModel(tabla);
    }

    public void borrarTabla() {
        int a = tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tabla.removeRow(i);
        }
    }

    public void agregarMateria() {
        Materia lista = new Materia();
        for (Iterator<Materia> it = listaM.iterator(); it.hasNext();) {
            lista = it.next();
            jComboMateria.addItem(lista.getIdMateria() + " " + lista.getNombre() + " " + lista.getAnio() + " " + lista.isEstado());
        }
    }
}
