/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.AlumnoData;
import persistencia.InscripcionData;
import persistencia.MateriaData;

/**
 *
 * @author thefl
 */
public class ViewNotas extends javax.swing.JInternalFrame {

    private List<Alumno> listaA;
    private DefaultTableModel tabla;
    private static AlumnoData alumnoData;
    private static MateriaData materiaData;
    private static InscripcionData inscripData;

    /**
     * Creates new form ViewNotas
     */
    public ViewNotas() {
        initComponents();
        tabla = new DefaultTableModel();
        alumnoData = new AlumnoData();
        inscripData = new InscripcionData();
        materiaData = new MateriaData();
        crearTabla();
        listaA = (ArrayList<Alumno>) alumnoData.listarAlumnos();
        agregarAlumno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbNotas = new javax.swing.JLabel();
        lbAlumno = new javax.swing.JLabel();
        jComboAlumno = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JTable();
        bGuardar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lbNotas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbNotas.setText("Carga de Notas");

        lbAlumno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbAlumno.setText("Alumno");

        jComboAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAlumnoActionPerformed(evt);
            }
        });

        jLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Materia", "Nota"
            }
        ));
        jScrollPane2.setViewportView(jLista);

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbAlumno)
                                .addGap(18, 18, 18)
                                .addComponent(jComboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(lbNotas)))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbNotas)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAlumno)
                    .addComponent(jComboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar)
                    .addComponent(bSalir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void jComboAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAlumnoActionPerformed
        borrarTabla();
        String selectedItem = jComboAlumno.getSelectedItem().toString();
        String[] parts = selectedItem.split(" ");
        int id = Integer.parseInt(parts[0]);
        List<Inscripcion> lisa = new ArrayList<>();
        Materia mat;
        String fila[] = new String[3];
        lisa = inscripData.obtenerInscripcionesPorAlumno(id);
        for (int i = 0; i < lisa.size(); i++) {
            fila[0] = lisa.get(i).getMateriaId().getIdMateria() + "";
            mat = materiaData.buscarMateria(lisa.get(i).getMateriaId().getIdMateria());
            fila[1] = mat.getNombre();
            fila[2] = lisa.get(i).getNota() + "";
            tabla.addRow(fila);
        }
        jLista.setModel(tabla);
    }//GEN-LAST:event_jComboAlumnoActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        try{
        String selectedItem = jComboAlumno.getSelectedItem().toString();
        String[] parts = selectedItem.split(" ");
        int idA = Integer.parseInt(parts[0]);
        int filaSelec = jLista.getSelectedRow();
        String idMatString = (String) tabla.getValueAt(filaSelec, 0);
        int idMat = Integer.parseInt(idMatString);
        int filaSelec2 = jLista.getSelectedRow();
        String idMatString2 = (String) tabla.getValueAt(filaSelec2, 2);
        double nota = Double.parseDouble(idMatString2);
        inscripData.actualizarNota(idA, idMat, nota);
        borrarTabla();
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "ERROR: Falto dar ENTER "+ex.getMessage());
        }
    }//GEN-LAST:event_bGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> jComboAlumno;
    private javax.swing.JTable jLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbAlumno;
    private javax.swing.JLabel lbNotas;
    // End of variables declaration//GEN-END:variables

    public void crearTabla() {
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("nombre");
        columnas.add("nota");
        for (Object iter : columnas) {
            tabla.addColumn(iter);
        }
        jLista.setModel(tabla);
    }

    public void borrarTabla() {
        int a = tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tabla.removeRow(i);
        }
    }

    public void agregarAlumno() {
        Alumno lista = new Alumno();
        for (Iterator<Alumno> it = listaA.iterator(); it.hasNext();) {
            lista = it.next();
            jComboAlumno.addItem(lista.getIdAlumno() + " " + lista.getApellido() + " " + lista.getNombre() + " " + lista.getDni());
        }
    }
}
